services:
    mongodb:
        image: mongo:latest
        container_name: my-mongo-container_name
        restart: always
        volumes:
            - ~/data/docker/mongodb:/data/db
        ports:
            - 27017
    sample_brambljs_service:
        build: .
        ports: 
            - "127.0.0.1:8082:8082"
        container_name: sample_brambljs_service
        depends_on: 
            - mongodb
        restart: always
    bifrost: 
        image: toplprotocol/bifrost:1.3.3
        container_name: bifrost
        ports:
            - "9085:9085"
            - "9084:9084"
        restart: always
        command: java -jar bifrost-1.3.3.jar -f --seed test --apiKeyHash BWz6Gw6gnb4NXzfgie8fetjk3m4xHyS5oV16GtHXptE4

